# Lattice HUB bootstrap (Windows PowerShell). Installs the controller on a FRESH
# machine - no hub need already be running. The binary is pulled from GitHub
# Releases (not served by a hub), the config + token are initialized, a free
# port is chosen, and the hub is installed as a persistent Scheduled Task.
#
# Usage:  irm https://raw.githubusercontent.com/shleesauce/lattice/master/install/get.ps1 | iex
#
# The download base is overridable for local testing:
#   $env:LATTICE_DOWNLOAD_BASE='http://localhost:8000'; irm .../get.ps1 | iex
$ErrorActionPreference = 'Stop'

$Base = if ($env:LATTICE_DOWNLOAD_BASE) { $env:LATTICE_DOWNLOAD_BASE } else { 'https://github.com/shleesauce/lattice/releases/latest/download' }

# Lattice ships a single amd64 Windows build.
$binName = 'lattice-windows-amd64.exe'
$installDir = Join-Path $env:LOCALAPPDATA 'Lattice'
$binPath = Join-Path $installDir 'lattice.exe'
New-Item -ItemType Directory -Force -Path $installDir | Out-Null

$url = "$Base/$binName"
Write-Host "lattice: downloading $url"
$tmp = "$binPath.download"
# Clean up the temp download on any failure (errors are terminating here).
try {
  Invoke-WebRequest -Uri $url -OutFile $tmp -UseBasicParsing
  if (-not (Test-Path $tmp) -or (Get-Item $tmp).Length -eq 0) {
    throw "downloaded binary is empty (download failed?): $url"
  }

  # --- verify against SHA256SUMS (fail closed) ---
  # Reach parity with the self-updater: never run an unverified binary.
  Write-Host "lattice: verifying checksum"
  $sumsTmp = "$binPath.sha256sums"
  try {
    Invoke-WebRequest -Uri "$Base/SHA256SUMS" -OutFile $sumsTmp -UseBasicParsing
  } catch {
    throw "could not fetch $Base/SHA256SUMS - refusing to install unverified binary"
  }
  # Extract the expected hash for THIS asset. SHA256SUMS lines are:
  #   <64-hex><two spaces><filename>
  $expected = $null
  foreach ($line in Get-Content -Path $sumsTmp) {
    if ($line -match "^([0-9a-fA-F]{64})  $([regex]::Escape($binName))$") {
      $expected = $matches[1]
      break
    }
  }
  Remove-Item -Force -Path $sumsTmp -ErrorAction SilentlyContinue
  if (-not $expected) {
    throw "no checksum entry for $binName in SHA256SUMS - refusing to install"
  }
  $actual = (Get-FileHash -Path $tmp -Algorithm SHA256).Hash
  if ($expected.ToLower() -ne $actual.ToLower()) {
    throw "checksum MISMATCH for ${binName}: expected $expected actual $actual - refusing to install"
  }
  Write-Host "lattice: checksum verified"
} catch {
  Remove-Item -Force -Path $tmp -ErrorAction SilentlyContinue
  throw "lattice: $_"
}

# Replace any running binary cleanly. Use the native cmdlet (not schtasks.exe):
# under $ErrorActionPreference='Stop', schtasks' stderr on a not-yet-existing
# task becomes a terminating error. Stop-ScheduledTask respects -ErrorAction.
Stop-ScheduledTask -TaskName 'LatticeHub' -ErrorAction SilentlyContinue
Get-Process -Name 'lattice' -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
# Retry the move: a stopped process may not release its file handle instantly,
# so a single fixed sleep can race. Retry a few times with a short wait.
$moved = $false
for ($i = 0; $i -lt 10; $i++) {
  try {
    Move-Item -Force -Path $tmp -Destination $binPath
    $moved = $true
    break
  } catch {
    Start-Sleep -Milliseconds 300
  }
}
if (-not $moved) {
  Remove-Item -Force -Path $tmp -ErrorAction SilentlyContinue
  throw "lattice: could not install binary to $binPath (file may be locked by a running process)"
}
Write-Host "lattice: installed binary at $binPath"

# Initialize config + token + free port.
& $binPath hub init

# Parse the chosen addr (e.g. ":7400") from the config the init just wrote.
$configPath = Join-Path $env:USERPROFILE '.lattice\config.json'
$addr = ':7400'
try {
  $cfg = Get-Content -Raw -Path $configPath | ConvertFrom-Json
  if ($cfg.addr) { $addr = $cfg.addr }
} catch { }
$port = $addr.TrimStart(':')

# Register an always-on scheduled task and start it now. Mirrors the macOS
# launchd LaunchAgent: start at BOTH logon and boot so the hub comes up even
# after a headless reboot, and restart-on-failure (999x @1min) for KeepAlive
# parity. Runs as the interactive user (NOT SYSTEM).
$taskName = 'LatticeHub'

# Launch via a hidden wscript wrapper so the console-subsystem hub binary never
# pops a visible, focus-stealing window on (re)launch. wscript.exe is GUI-subsystem
# (no console of its own) and starts the child with SW_HIDE; bWaitOnReturn=$true
# keeps the task tracking the live process, so RestartCount / MultipleInstances=
# IgnoreNew semantics are unchanged.
$vbsPath = Join-Path $installDir 'run-hub-hidden.vbs'
$runCmd  = "`"$binPath`" hub"
$vbsEsc  = $runCmd -replace '"', '""'
$vbsBody = @"
' Lattice hub launcher - runs the hub hidden (no console window). Auto-generated by get.ps1.
Dim sh : Set sh = CreateObject("WScript.Shell")
WScript.Quit sh.Run("$vbsEsc", 0, True)
"@
Set-Content -Path $vbsPath -Value $vbsBody -Encoding ASCII
$action  = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument "`"$vbsPath`""
$triggers = @(
  (New-ScheduledTaskTrigger -AtLogOn),
  (New-ScheduledTaskTrigger -AtStartup)
)
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew
# Bind to THIS machine's local account ("<ComputerName>\<user>").
$principal = New-ScheduledTaskPrincipal -UserId "$($env:COMPUTERNAME)\$($env:USERNAME)" -LogonType Interactive -RunLevel Highest

# Idempotent: drop any prior registration first.
Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue

try {
  Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $triggers -Settings $settings -Principal $principal `
    -Description 'Lattice hub' -Force | Out-Null
  Start-ScheduledTask -TaskName $taskName
  Write-Host "lattice: scheduled task '$taskName' installed (logon+boot, restart-on-fail) and started"
}
catch {
  Write-Warning "lattice: scheduled task registration failed ($_); starting detached process instead"
  Start-Process -FilePath $binPath -ArgumentList 'hub' -WindowStyle Hidden
}

# --- enroll THIS machine as an agent too ---
# So the dashboard is populated and fully working out of the box (live metrics,
# terminal, editor) instead of an empty fleet the operator has to figure out how
# to fill. The hub host running its own agent is the normal pattern; it reaches
# the hub over loopback, so this needs NO Tailscale. Wrapped so any hiccup here is
# non-fatal: the hub is already installed above and must never be undone by it.
try {
  $tokenPath = Join-Path $env:USERPROFILE '.lattice\.lattice-token'
  $token = (Get-Content -Raw -Path $tokenPath -ErrorAction Stop).Trim()
  if ([string]::IsNullOrWhiteSpace($token)) { throw 'token file empty' }

  $agentName = $env:COMPUTERNAME
  $agentHub  = "127.0.0.1:$port"
  Stop-ScheduledTask -TaskName 'LatticeAgent' -ErrorAction SilentlyContinue

  # Token is injected into the agent's PROCESS env by the hidden VBS wrapper (not
  # the command line), matching the served agent installer.
  $agentArgs = "agent --hub $agentHub --name `"$agentName`""
  $aVbsPath  = Join-Path $installDir 'run-agent-hidden.vbs'
  $aRunCmd   = "`"$binPath`" $agentArgs"
  $aVbsEsc   = $aRunCmd -replace '"', '""'
  $aTokenEsc = $token -replace '"', '""'
  $aVbsBody = @"
' Lattice agent launcher - runs the agent hidden (no console window). Auto-generated by get.ps1.
Dim sh : Set sh = CreateObject("WScript.Shell")
sh.Environment("PROCESS")("LATTICE_TOKEN") = "$aTokenEsc"
WScript.Quit sh.Run("$aVbsEsc", 0, True)
"@
  Set-Content -Path $aVbsPath -Value $aVbsBody -Encoding ASCII
  icacls $aVbsPath /inheritance:r /grant:r "$($env:USERNAME):F" | Out-Null

  $aAction   = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument "`"$aVbsPath`""
  $aTriggers = @((New-ScheduledTaskTrigger -AtLogOn), (New-ScheduledTaskTrigger -AtStartup))
  $aSettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew
  $aPrincipal = New-ScheduledTaskPrincipal -UserId "$($env:COMPUTERNAME)\$($env:USERNAME)" -LogonType Interactive -RunLevel Highest
  Unregister-ScheduledTask -TaskName 'LatticeAgent' -Confirm:$false -ErrorAction SilentlyContinue
  Register-ScheduledTask -TaskName 'LatticeAgent' -Action $aAction -Trigger $aTriggers -Settings $aSettings -Principal $aPrincipal `
    -Description 'Lattice agent' -Force | Out-Null
  Start-ScheduledTask -TaskName 'LatticeAgent'
  Write-Host "lattice: this machine is enrolled as agent '$agentName' - it'll appear in your fleet automatically"
}
catch {
  Write-Warning "lattice: local agent enroll skipped ($_); the hub is running - add this machine from the dashboard"
}

Write-Host ""
Write-Host "lattice: hub + this machine are up and running."
Write-Host "lattice: open  http://$($env:COMPUTERNAME):$port/  to finish setup (your machine is already in the fleet)."
